[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "pybind11>=2.7.1",
    "scikit-build",
    "cmake",
    "ninja",
    "setuptools_scm>=6.2"
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
