name: Build CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Checkout Current Repo
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get install python-dev libboost-python-dev python-setuptools
        python -m pip install --upgrade pip
        python -m pip install wheel
    - name: Pip install pylint, RPi.GPIO, Sphinx, & sphinx-rtd-theme RPi.GPIO
      run: |
        pip install pylint Sphinx sphinx-rtd-theme
    - name: Library version
      run: git describe --dirty --always --tags
    # - name: check python examples PEP8 compliance
    #   run: |
    #     pylint examples/*.py --disable=invalid-name,no-name-in-module,no-member,duplicate-code
      # invalid-name,no-name-in-module,no-member are errors related to C++ wrapped into a python package; Applies to RPi.GPIO package as well.
      # duplicate-code error gets flagged because some examples use similar code snippets
    - name: Build docs
      working-directory: docs
      run: sphinx-build -E -W -b html . _build/html
