name: Build CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Checkout Current Repo
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get install python3-dev
          python3 -m pip install --upgrade pip pylint
          python3 -m pip install -r docs/requirements.txt

      - name: Library version
        run: git describe --dirty --always --tags

      - name: Build package for docs extraction and linting examples
        run: python3 -m pip install .

      - name: check python examples PEP8 compliance
        run: |
          pylint examples/*.py --disable=duplicate-code
        # duplicate-code error gets flagged because some examples use similar code snippets

      - name: Build docs
        working-directory: docs
        run: sphinx-build -E -W -b html . _build/html

      - name: upload to github pages
        # if: ${{ github.event_name == 'release'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html

      - name: Validate distribution
        run: |
          python3 -m pip install -r requirements.txt twine
          python3 setup.py bdist
          twine check dist/*
