name: Release Actions

on:
  release:
    types: [published]

jobs:
  upload-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Checkout Current Repo
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt install python-dev
          python3 -m pip install --upgrade pip

      # - name: Build and publish
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.pypi_token }}
      #   run: |
      #     python setup.py sdist
      #     twine upload dist/*
