name: Release Actions

on:
  release:
    types: [published]

jobs:
  upload-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Checkout Current Repo
        uses: actions/checkout@v1
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt install python3-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: build binary distributable wheel
        run: python setup.py bdist_wheel

      - name: Save distributable wheels as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "pyRF24_pkg_dist"
          path: ${{ github.workspace }}/dist

      ###### We need a self-hosted runner to build distributable wheels for armv7l
      # - name: Publish to PyPi
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.pypi_token }}
      #   run: |
      #     twine upload dist/*
